name: Run the Action on each commit
on:
  push:
    branches:
    - feature-1

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: docker://ghcr.io/repo-sync/pull-request:v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}         # Required to use container image
